#!/usr/bin/env node
// Vendors the DESIGN.md spec from its upstream source of truth into this skill
// so it travels in a single submodule. Run by .github/workflows/sync-upstream.yml
// and locally.
//
// Source of truth: github.com/google-labs-code/design.md -> docs/spec.md
//
// Provenance lives in git history: the workflow records the exact upstream
// commit in the sync commit message. This script never edits SKILL.md.

import { mkdir, writeFile, appendFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REFS = path.join(ROOT, "references");

const REPO = "google-labs-code/design.md";
const BRANCH = "main";
const SPEC_PATH = "docs/spec.md";
const SOURCE_URL = `https://github.com/${REPO}/blob/${BRANCH}/${SPEC_PATH}`;

const BANNER =
  "<!-- Generated by scripts/sync.mjs from google-labs-code/design.md (docs/spec.md). Do not edit by hand; it is overwritten on every sync. The exact upstream commit is recorded in this file's sync commit. -->";

async function getJson(url) {
  const res = await fetch(url, {
    headers: {
      "User-Agent": "design-md-sync",
      Accept: "application/vnd.github+json",
      ...(process.env.GITHUB_TOKEN
        ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
        : {}),
    },
  });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
  return res.json();
}

async function getText(url) {
  const res = await fetch(url, { headers: { "User-Agent": "design-md-sync" } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
  return res.text();
}

async function main() {
  await mkdir(REFS, { recursive: true });

  // Resolve the upstream commit so the fetch is consistent and recordable.
  const commit = await getJson(
    `https://api.github.com/repos/${REPO}/commits/${BRANCH}`,
  );
  const sha = commit.sha;

  const spec = await getText(
    `https://raw.githubusercontent.com/${REPO}/${sha}/${SPEC_PATH}`,
  );

  const out = `${BANNER}\n\n_Source: ${SOURCE_URL}_\n\n${spec.trim()}\n`;
  await writeFile(path.join(REFS, "spec.md"), out, "utf8");
  console.log(`wrote references/spec.md (from ${REPO}@${sha})`);

  if (process.env.GITHUB_OUTPUT) {
    await appendFile(process.env.GITHUB_OUTPUT, `upstream_sha=${sha}\n`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
